name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha dos commits
        uses: Platane/snk@v3
        with:
          github_user_name: Kaiki2004
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#64ffda"
          color_dots: "#d1d5db,#6ee7b7,#3b82f6,#9333ea,#f43f5e"
          pixels_per_day: 20

      - name: Commit e push para o branch de saída
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
