name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite UTC
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha dos commits
        uses: Platane/snk@v3
        with:
          github_user_name: Kaiki2004
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit e push para o branch de saída
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
