name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha estilo Matrix
        uses: Platane/snk@v3
        with:
          github_user_name: Kaiki2004
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#00FF41"             # Verde Matrix
          color_dots: "#000000,#003300,#006600,#00cc00,#00ff41"  # degradê Matrix
          background_color: "#000000"        # Fundo preto
          pixels_per_day: 20                 # Grade mais detalhada

      - name: Push para o branch de saída
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
