name: Generate Snake 🐍

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a cobrinha personalizada
        uses: Platane/snk@v3
        with:
          github_user_name: Kaiki2004
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: "#9333ea"           # Roxo vibrante
          color_dots: "#000000,#1f1f1f,#333333,#4b4b4b,#666666"  # degrade escuro
          background_color: "#000000"
          pixels_per_day: 20               # Mais definição

      - name: Push para o branch de saída
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
